### ISSUE TITLE
panic: error generating pkgs

### ISSUE THREAD

**Issue by tim-goto** [nix-community/gomod2nix#172]
Hey, thanks for the great tool :) Unfortunately I have an issue creating the `toml` file for [this](https://github.com/veertuinc/anklet) repo. To reproduce:
```
git clone https://github.com/veertuinc/anklet.git
pushd anklet
nix shell github:nix-community/gomod2nix
gomod2nix generate
```
results in this output:
```
INFO[0000] Parsing go.mod                                modPath=go.mod
INFO[0000] Downloading dependencies
panic: error generating pkgs: exit status 1

goroutine 1 [running]:
github.com/nix-community/gomod2nix/internal/cmd.generateFunc(0xb23dc0?, {0xb5a2c8?, 0x0?, 0x0?})
        /build/source/internal/cmd/root.go:67 +0x416
github.com/spf13/cobra.(*Command).execute(0xb23dc0, {0xb5a2c8, 0x0, 0x0})
        /build/source/vendor/github.com/spf13/cobra/command.go:987 +0xaa7
github.com/spf13/cobra.(*Command).ExecuteC(0xb23ae0)
        /build/source/vendor/github.com/spf13/cobra/command.go:1115 +0x417
github.com/spf13/cobra.(*Command).Execute(...)
        /build/source/vendor/github.com/spf13/cobra/command.go:1039
github.com/nix-community/gomod2nix/internal/cmd.Execute()
        /build/source/internal/cmd/root.go:124 +0x25
main.main()
        /build/source/main.go:6 +0x17
```
do you have any idea what might be wrong here? Thanks!

**Comment by i-am-logger** [comment]
i already had `1.23.0`
this fixed it for me: 
```nix
    gomod2nix.inputs.nixpkgs.follows = "nixpkgs";
```
